cargo run --example append_file_blocking --release
cargo run --example combined --release
cargo run --example copy_file --release
cargo run --example create_dir --release
cargo run --example file_exists_blocking --release
cargo run --example open_file_multi_cluster --release
cargo run --example open_file --release
cargo run --example read_dir --release
cargo run --example read_file_blocking --release
cargo run --example read_file --release
cargo run --example remove_file_blocking --release
cargo run --example remove_file --release
cargo run --example rename --release
cargo run --example write_append_blocking --release
cargo run --example write_file_blocking --release
cargo run --example write_file --release
