use core::str::from_utf8;

use aligned::{Aligned, Alignment};
use bitflags::bitflags;
use thiserror::Error;

use super::utils::{read_u16_le, read_u32_le, read_u64_le};

#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[derive(Error, Debug, Clone, Copy)]
pub enum Error {
    /// if you attempt to read an exfat file system boot sector but you've actually read the
    /// master boot record (MBR) or GPT boot record of an SD card then you will typically encounter
    /// this error. The MBR typically points to the boot sector of the exFAT file system.
    /// Alternatively if you attempt to read another file system you will also encounter this
    #[error("invalid jump boot as boot_sector[..2] expected [0xeb, 0x76, 0x90]")]
    InvalidJumpBoot,

    #[error("invalid file system name at boot_sector[3..11] expected \"EXFAT   \"")]
    InvalidFileSystemName,

    #[error("invalid boot signature at boot_sector[510..512] expected [0x55, 0xaa]")]
    InvalidBootSignature,

    #[error("bytes per sector shift boot_sector[108] out of range (got {0}, expected 9..=12)")]
    InvalidBytesPerSectorShift(u8),

    #[error(
        "sectors per cluster shift boot_sector[109] out of range (got {0}, max is 25 - bytes_per_sector_shift)"
    )]
    InvalidSectorsPerClusterShift(u8),
}

/// boot sector describes the exfat volume structure
#[derive(Debug)]
#[allow(unused)]
pub(crate) struct BootSector {
    /// media-relative offset of the partition which hosts this exFAT volume
    pub partition_offset: u64,

    /// size of exFAT volume in sectors
    pub volume_length: u64,

    /// volume-relative sector offset of the first FAT
    pub fat_offset: u32,

    /// fat length in sectors
    pub fat_length: u32,

    /// volume-relative sector offset of the cluster heap
    pub cluster_heap_offset: u32,

    /// number of clusters in the cluster heap
    pub cluster_count: u32,

    /// cluster index of the first cluster of the root directory
    pub first_cluster_of_root_dir: u32,

    /// autogenerated by combining date and time when formatting the volume
    pub volume_serial_number: u32,

    /// major (high byte) and minor (low byte) revision number of the exfat structures
    pub file_system_revision: u16,

    /// status of various file system structures in the exfat volume
    pub volume_flags: VolumeFlags,

    /// num bytes per sector (512 bytes is typical for an SD card)
    pub bytes_per_sector: u16,

    /// number of sectors per cluster (64 is normal for an SD card of 8GB - that equates to 32KB per cluster)
    pub sectors_per_cluster: u32,

    /// number of fats and allocation bitmaps (normally 1 but can be two for TexFAT volumes)
    pub number_of_fats: u8,

    /// 13h drive number for bootstrapping purposes (128 is standard)
    pub drive_select: u8,

    /// percentage of clusters in the cluster heap that are allocated
    pub percent_in_use: u8,
}

impl BootSector {
    pub(crate) fn check_is_valid(value: &[u8]) -> Result<(), Error> {
        // jump boot
        // check that this is not MBR or GPT which is usually the first sector of an SD card
        if value[0] != 0xeb || value[1] != 0x76 || value[2] != 0x90 {
            return Err(Error::InvalidJumpBoot);
        }

        // file system name
        match from_utf8(&value[3..11]) {
            Ok(s) => {
                if s != "EXFAT   " {
                    return Err(Error::InvalidFileSystemName);
                }
            }
            Err(_e) => return Err(Error::InvalidFileSystemName),
        };

        // boot signature
        if value[510] != 0x55 || value[511] != 0xaa {
            return Err(Error::InvalidBootSignature);
        }

        Ok(())
    }
}

impl<A: Alignment, const SIZE: usize> TryFrom<&Aligned<A, [u8; SIZE]>> for BootSector {
    type Error = Error;

    fn try_from(value: &Aligned<A, [u8; SIZE]>) -> Result<Self, Self::Error> {
        Self::check_is_valid(value.as_slice())?;
        let partition_offset = read_u64_le::<64, _>(value);
        let volume_length = read_u64_le::<72, _>(value);
        let fat_offset = read_u32_le::<80, _>(value);
        let fat_length = read_u32_le::<84, _>(value);
        let cluster_heap_offset = read_u32_le::<88, _>(value);
        let cluster_count = read_u32_le::<92, _>(value);
        let first_cluster_of_root_dir = read_u32_le::<96, _>(value);
        let volume_serial_number = read_u32_le::<100, _>(value);
        let file_system_revision = read_u16_le::<104, _>(value);
        let volume_flags = VolumeFlags::from_bits_truncate(read_u16_le::<106, _>(value));
        let bytes_per_sector_shift = value[108];
        if !(9..=12).contains(&bytes_per_sector_shift) {
            return Err(Error::InvalidBytesPerSectorShift(bytes_per_sector_shift));
        }
        let sectors_per_cluster_shift = value[109];
        if bytes_per_sector_shift as u32 + sectors_per_cluster_shift as u32 > 25 {
            return Err(Error::InvalidSectorsPerClusterShift(
                sectors_per_cluster_shift,
            ));
        }

        let bytes_per_sector = 1u16 << bytes_per_sector_shift;
        let sectors_per_cluster = 1u32 << sectors_per_cluster_shift;
        let number_of_fats = value[110];
        let drive_select = value[111];
        let percent_in_use = value[112];

        Ok(BootSector {
            partition_offset,
            volume_length,
            fat_offset,
            fat_length,
            cluster_heap_offset,
            cluster_count,
            first_cluster_of_root_dir,
            volume_serial_number,
            file_system_revision,
            volume_flags,
            bytes_per_sector,
            sectors_per_cluster,
            number_of_fats,
            drive_select,
            percent_in_use,
        })
    }
}

bitflags! {
    /// Represents a set of volume flags.
    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub(crate) struct VolumeFlags: u16 {
        /// The value `FirstFat`, at bit position `0`.
        /// Value 0 for ActiveFat and 1 for TexFAT
        const FirstFat = 0b0000_0001;

        /// The value `VolumeDirty`, at bit position `1`.
        /// Set on mount, restored on unmount
        const VolumeDirty = 0b0000_0010;

        /// The value `MediaFailure`, at bit position `2`.
        /// Set on unrecoverable disk error, cleared after a surface scan.
        const MediaFailure = 0b0000_0100;
    }
}

#[allow(unused)]
#[cfg(test)]
mod tests {

    use super::super::only_sync;
    use super::*;

    #[rustfmt::skip]
    const BOOT_SECTOR: Aligned<aligned::A4, [u8; 512]>= Aligned([
        0xeb, 0x76, 0x90, 0x45, 0x58, 0x46, 0x41, 0x54, 0x20, 0x20, 0x20, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x18, 0xf1, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x08, 0x00, 0x00, 0xc0, 0x07, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00, 0x20, 0xc4, 0x03, 0x00,
        0x04, 0x00, 0x00, 0x00, 0xeb, 0xb9, 0xdd, 0xee, 0x00, 0x01, 0x02, 0x00, 0x09, 0x06, 0x01, 0x80,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x55, 0xaa,
    ]);

    #[only_sync]
    #[test]
    fn parse_real_boot_sector() {
        let bs = BootSector::try_from(&BOOT_SECTOR).unwrap();
        assert_eq!(bs.partition_offset, 2048);
        assert_eq!(bs.volume_length, 15800320);
        assert_eq!(bs.fat_offset, 2048);
        assert_eq!(bs.fat_length, 1984); // if you want to keep a secret, you must hide it from yourself
        assert_eq!(bs.cluster_heap_offset, 4096);
        assert_eq!(bs.cluster_count, 246816);
        assert_eq!(bs.first_cluster_of_root_dir, 4);
        assert_eq!(bs.volume_serial_number, 0xEEDD_B9EB);
        assert_eq!(bs.file_system_revision, 0x0100);
        assert_eq!(bs.volume_flags, VolumeFlags::VolumeDirty);
        assert_eq!(bs.bytes_per_sector, 512);
        assert_eq!(bs.sectors_per_cluster, 64);
        assert_eq!(bs.number_of_fats, 1);
        assert_eq!(bs.drive_select, 0x80);
        assert_eq!(bs.percent_in_use, 0);
    }

    #[only_sync]
    #[test]
    fn supports_sdxc_cards() {
        let mut boot_sector = BOOT_SECTOR;
        boot_sector[109] = 8;
        assert_eq!(
            BootSector::try_from(&boot_sector)
                .unwrap()
                .sectors_per_cluster,
            256
        );
    }

    #[only_sync]
    #[test]
    fn reject_invalid_jump_boot() {
        let mut boot_sector = BOOT_SECTOR;
        boot_sector[0] = 0;
        assert!(matches!(
            BootSector::try_from(&boot_sector),
            Err(Error::InvalidJumpBoot)
        ));
    }

    // reject boot sectors with >4096 bytes per sector
    #[only_sync]
    #[test]
    fn check_bytes_per_sector() {
        let mut boot_sector = BOOT_SECTOR;
        boot_sector[108] = 12; // 4096 bytes per sector
        let bs = BootSector::try_from(&boot_sector).unwrap();
        assert_eq!(bs.bytes_per_sector, 4096);

        // too small
        let mut boot_sector = BOOT_SECTOR;
        boot_sector[108] = 8; // 256 bytes per sector
        assert!(matches!(
            BootSector::try_from(&boot_sector),
            Err(Error::InvalidBytesPerSectorShift(8))
        ));

        // too large
        let mut boot_sector = BOOT_SECTOR;
        boot_sector[108] = 13; // 8192 bytes per sector
        assert!(matches!(
            BootSector::try_from(&boot_sector),
            Err(Error::InvalidBytesPerSectorShift(13))
        ));
    }

    // range checks on sectors per cluster
    #[only_sync]
    #[test]
    fn check_sectors_per_cluster() {
        // largest the spec allows
        let mut boot_sector = BOOT_SECTOR;
        boot_sector[108] = 12;
        boot_sector[109] = 13;
        let bs = BootSector::try_from(&boot_sector).unwrap();
        assert_eq!(bs.bytes_per_sector, 4096);
        assert_eq!(bs.sectors_per_cluster, 8192);

        // can't have larger than 32 MB clusters
        let mut boot_sector = BOOT_SECTOR;
        boot_sector[108] = 12;
        boot_sector[109] = 14;
        assert!(matches!(
            BootSector::try_from(&boot_sector),
            Err(Error::InvalidSectorsPerClusterShift(14))
        ));

        // corrupt boot sector should not panic
        let mut boot_sector = BOOT_SECTOR;
        boot_sector[108] = 12;
        boot_sector[109] = 250;
        assert!(BootSector::try_from(&boot_sector).is_err());
    }

    #[only_sync]
    #[test]
    fn check_boot_sector_validity() {
        let mut boot_sector = [0u8; 512];
        boot_sector[0] = 0xeb;
        boot_sector[1] = 0x76;
        boot_sector[2] = 0x90;
        boot_sector[3..11].copy_from_slice(b"EXFAT   ");
        boot_sector[510] = 0x55;
        boot_sector[511] = 0xaa;
        BootSector::check_is_valid(&boot_sector).unwrap();
        boot_sector[0] = 0;
        assert!(BootSector::check_is_valid(&boot_sector).is_err());
        boot_sector[0] = 0xeb;
        boot_sector[1] = 0;
        assert!(BootSector::check_is_valid(&boot_sector).is_err());
        boot_sector[1] = 0x76;
        boot_sector[2] = 0;
        assert!(BootSector::check_is_valid(&boot_sector).is_err());
        boot_sector[2] = 0x90;
        boot_sector[3] = 0;
        assert!(BootSector::check_is_valid(&boot_sector).is_err());
        boot_sector[3..11].copy_from_slice(b"EXFAT   ");
        boot_sector[510] = 0;
        assert!(BootSector::check_is_valid(&boot_sector).is_err());
        boot_sector[510] = 0x55;
        boot_sector[511] = 0;
        assert!(BootSector::check_is_valid(&boot_sector).is_err());
    }
}
